<?php
	$GLOBALS['ARR_ACTION'] = array(
		'view'		=>1,
		'add'		=>2,
		'edit'		=>4,
		'delete'	=>8
		);
	$GLOBALS['ARR_ACTION_NAME'] = array(
		'view'		=>'Xem',
		'add'		=>'Thêm',
		'edit'		=>'Sửa',
		'delete'	=>'Xóa'
		);
	$GLOBALS['ARR_COM'] = array(
		'config'	=>1,
		'gusers'	=>2,
		'user'		=>4,
		'menus'		=>8,
		'mnuitem'	=>16,
		'category'	=>32,
		'contents'	=>64,
		'cate_intro'	=>128,
		'intro'			=>256,
		'cate_service'	=>512,
		'service'		=>1024,
		'guide'			=>2048,
		'cate_guide'	=>4096,
		'partner'		=>8192,
		'cate_partner'	=>16384,
		'question'		=>32768,
		'question_group'	=>65536,
		'document'		=>131072,
		'document_type'	=>262144,
		'recruitment'	=>524288,
		'slider'		=>1048576,
		'module'		=>2097152,
		'mail'			=>4194304
		);
	$GLOBALS['ARR_COM_ACT'] = array(
		'config'	=>4, // edit
		'gusers'	=>15, 
		'user'		=>15, 
		'menus'		=>15, 
		'mnuitem'	=>15,
		'category'	=>15,
		'contents'	=>15,
		'cate_intro'	=>15,
		'intro'			=>15,
		'cate_service'	=>15,
		'service'		=>15,
		'guide'			=>15,
		'cate_guide'	=>15,
		'partner'		=>15,
		'cate_partner'	=>15,
		'question'		=>15,
		'question_group'	=>15,
		'document'		=>15,
		'document_type'	=>15,
		'recruitment'	=>15,
		'slider'		=>15,
		'module'		=>15,
		'mail'			=>15
		);
	$GLOBALS['ARR_COM_NAME'] = array(
		'config'	=>'Cấu hình website',
		'gusers'	=>'Nhóm quản trị',
		'user'		=>'Thành viên quản trị',
		'menus'		=>'Menu chính',
		'mnuitem'	=>'Menu con',
		'category'	=>'Nhóm tin',
		'contents'	=>'Bài viết',
		'cate_intro'	=>'Nhóm giới thiệu',
		'intro'			=>'Giới thiệu',
		'cate_service'	=>'Nhóm dịch vụ',
		'service'		=>'Dịch vụ',
		'guide'			=>'Hướng dẫn',
		'cate_guide'	=>'Nhóm hướng dẫn',
		'partner'		=>'Đối tác',
		'cate_partner'	=>'Nhóm đối tác',
		'question'		=>'Hỏi đáp',
		'question_group'	=>'Nhóm hỏi đáp',
		'document'		=>'Tài liệu',
		'document_type'	=>'Loại tài liệu',
		'recruitment'	=>'Tuyển dụng',
		'slider'		=>'Banner',
		'module'		=>'Chức năng',
		'mail'			=>'Mail'
		);
	$GLOBALS['MSG_PERMIS']='<div id="action" style="background-color:#fff; margin:10px 15px;"><h3 align="center">Bạn không có quyền truy cập.</h3></div>';
?>